language: ruby
rvm:
- 2.1.2
addons:
  postgresql: '9.3'
  code_climate:
    repo_token:
      secure: SEMurEAFPYHZCi/ZFfY/nLB+SDYUVoz8gWnLH6jVPrpS3RLoK8vvM4PutdX8URCet30+xRYGHWd7NQ2QDc2nL1IWMWoj9cyZ+Sc/+JeHAmtsOyVJl/yJ6MHSYqN7iRYnUwx31NH650yfzy/bRWHmGhK9CkM7J1LWsxpQ/P7Yqgc=
before_script:
- cp config/database.yml.travis config/database.yml
- bundle exec rake db:setup
script: bundle exec rspec spec
env:
  global:
  - coveralls: true
  - secure: TROUE2OfEoMMjlfoiA54NRxwSq6//WH+Ph2LGMWtmnZvE0X5VK0uROTwi+bl3zVr9Zzq+Q5oa90iZUJdW5gBwJq8bJ0htOkNajSlTVGrhHun83T/kc2DLjgiZ2y66F8b0hnnJDSO4c75GDU2k0sZNOuHOOWqvYfE8+Q83Ah+plQ=
